//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Helpers;
using System.Web.Security;
using System.Web.UI;
using System.Web.WebPages;
using System.Web.WebPages.Html;

public class _Page_Registro_cshtml : System.Web.WebPages.WebPage {
private static object @__o;
#line hidden
public _Page_Registro_cshtml() {
}
protected System.Web.HttpApplication ApplicationInstance {
get {
return ((System.Web.HttpApplication)(Context.ApplicationInstance));
}
}
public override void Execute() {

#line 1 "C:\Users\Marco\AppData\Local\Temp\67675781B34D31B4BBD5CB11B4D4BF059D9A\3\Progra5Jaz\Progra5Jaz\Views\Home\Registro.cshtml"
  
    Layout = null;


#line default
#line hidden

#line 2 "C:\Users\Marco\AppData\Local\Temp\67675781B34D31B4BBD5CB11B4D4BF059D9A\3\Progra5Jaz\Progra5Jaz\Views\Home\Registro.cshtml"
             __o = ViewBag.Message;


#line default
#line hidden

#line 3 "C:\Users\Marco\AppData\Local\Temp\67675781B34D31B4BBD5CB11B4D4BF059D9A\3\Progra5Jaz\Progra5Jaz\Views\Home\Registro.cshtml"
            __o = ViewBag.icono;


#line default
#line hidden
}
}
}
